### PR TITLE
Add more powerUps

### PR DESCRIPTION
**Pull request by jim-rosales**
TODO:

- [x] Issue #106
- [x] Issue #101
- [x] Issue #98

### CODE REVIEW

**Comment by michaelosbornegit** [comment]
I might be testing this before it's ready, but right now I get this error when I try to shoot a second enemy

image

I love what you did with the control display though, that cleans it up compared to having directions separate 👍

**Comment by jim-rosales** [comment]
Ohhhh yeah, I just saw that actually. It should be fixed in my next push

**Comment by jim-rosales** [comment]
I'm just adding some comments to the functions I added. 

So which this push, a player can only hold a single homing missile and if they already have one we won't drop any homing missile power-ups since it seemed unnecessary 

Working on the chain-gun or multi gun power up next

**Comment by codemalone** [comment]
I'm going to attempt a merge with the current multi-weapon functionality so we have bleeding updated. I want to work on level development today using all combined work.

**Pull request merged**
