### PR TITLE
WIP: Cookies!

### PR DESCRIPTION
**Pull request by jim-rosales**
@codemalone you were right in the fact that we could import a library to save info to cookies and it seems pretty trivial to save information on them

I have a simple example in this PR

Not sure if we want to go with this route for saving checkpoints or just store everything in a DB. What does everyone think?

https://github.com/js-cookie/js-cookie

### CODE REVIEW

**Comment by codemalone** [comment]
I think sites usually save some token in the cookie, and then lookup the associated data in a db. But really whatever is easiest is good with me.

**Comment by michaelosbornegit** [comment]
What is this an example of? if it works then awesome!

I was assuming checkpoints would be stored locally over the course of a game, and would reset when you refresh the page so in that case we wouldn't need anything fancy to store those.

What were you thinking?

**Comment by jim-rosales** [comment]
I was thinking we would save the checkpoints even if they left the page. So if they came back later they could still go to their last saved checkpoint

We would still be saving them locally but instead in a cookie since those persist in your browser. 

Example on how to save to a cookie
```JS
Cookies.set('checkPoint, 'wave4');
```

Retrieving the value works the same
```JS
Cookies.get('wave4');
```

**Comment by michaelosbornegit** [comment]
That would be pretty sweet, I like this idea!

**Pull request merged**
