### PR TITLE
new feature: Lines

### PR DESCRIPTION
**Pull request by codemalone**
The Line class is interchangeable with the Ring. I suggest that we keep defining these as ring.* to maintain compatibility. In the firing configuration,
  specify _**width**_ to define a linear arrangement
  specify **_spread_** to define an arc arrangement
  specify **neither** to define a full circle arrangement

This PR also includes
  bug fix for targetLeadShot
  **util/pattern.js** is a Node.js script to help create a pattern object

### CODE REVIEW

**Comment by codemalone** [comment]
the high line count is from _objects.js_ for some reason my commit replaced the whole file with the same copy. is this related to the carriage returns? @Jjim-rosales will you please check if my vscode messed it up? odd that it only happened for the one file.

**Comment by jim-rosales** [comment]
Most likely its related to vs code changing the end of line chars from LF to CLRF

**Comment by jim-rosales** [comment]
Just pulled your branch, if you check on VS code it will indicate which end of line character format it is using. You can also just click on that text and it'll let you update it

screen shot 2019-02-28 at 12 45 05 pm

**Comment by michaelosbornegit** [comment]
Looks good! I love the difficulty of avoiding the arrows and how they stay together! I say merge!

**Pull request merged**
